DROP DATABASE IF EXISTS BRDR;

CREATE DATABASE BRDR;

USE BRDR;

CREATE TABLE PERMISOS(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	usuario VARCHAR(50) NOT NULL,
	agregar BIT DEFAULT 0,
	editar BIT DEFAULT 0,
	eliminar BIT DEFAULT 0,
	permisos BIT DEFAULT 0

)ENGINE=InnoDB;

CREATE TABLE USUARIOS(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(255) NOT NULL,
	apellido VARCHAR(255) NOT NULL,
	usuario VARCHAR(50),
	email VARCHAR(255) UNIQUE,
	password VARCHAR(255),
	fecha TIMESTAMP,
	ultima_visita TIMESTAMP,
	activo BIT DEFAULT 1,
	FK_PERMISOS INT UNSIGNED,

	FOREIGN KEY(FK_PERMISOS) REFERENCES PERMISOS(id)
)ENGINE=InnoDB;

CREATE TABLE POSTS(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	texto VARCHAR(255) NOT NULL,
	fecha TIMESTAMP,
	activo BIT DEFAULT 1,
	FK_USUARIO INT UNSIGNED,

	FOREIGN KEY(FK_USUARIO) REFERENCES USUARIOS(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE COMENTARIOS(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	texto VARCHAR(255) NOT NULL,
	fecha TIMESTAMP,
	activo BIT DEFAULT 1,
	FK_POST INT UNSIGNED,
	FK_USUARIO INT UNSIGNED,

	FOREIGN KEY(FK_POST) REFERENCES POSTS(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FK_USUARIO) REFERENCES USUARIOS(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;

CREATE TABLE NOTIFICACIONES(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	accion VARCHAR(255) NOT NULL,
	fecha TIMESTAMP,
	FK_POST INT UNSIGNED,
	FK_USUARIO INT UNSIGNED,

	FOREIGN KEY(FK_POST) REFERENCES POSTS(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FK_USUARIO) REFERENCES USUARIOS(id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB;